name: Add to Project

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/add-to-project.yml@main
    secrets:
      org_project: ${{ secrets.ORGANIZATION_PROJECT }}