---
name: "Bump version (manually)"

on:
  # can be called manually from GH webpage
  workflow_dispatch:
    inputs:
      target_branch:
        default: 'main'
        description: "Branch on which the version bump is to be done."
        required: false

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/bump-version.yaml@main
    with:
      target_branch: ${{ inputs.target_branch }}